# Generated by Django 2.2.9 on 2020-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="fieldModel",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
